//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortener.DAOService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParsedUrl
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
        public System.DateTime CreateAt { get; set; }
        public long ClicksCount { get; set; }
    }
}
